### ISSUE TITLE
Tests fail with Python 3.11: AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by s3v-** [enthought/apptools#325]
Some tests start failing with Python 3.11.
See [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027503](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027503])

```python
> ======================================================================
> ERROR: Test the get_version function.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/tests/test_version_registry.py", line 69, in test_get_version
>     state = state_pickler.get_state(c)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 996, in get_state
>     s = dumps(obj)
>         ^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 968, in dumps
>     return StatePickler().dumps(value)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 308, in dumps
>     return pickle.dumps(self._do(value))
>                         ^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 358, in _do
>     return self._do_instance(obj)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 403, in _do_instance
>     state.pop("__traits_version__", None)
>     ^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'pop'
> 
> ======================================================================
> ERROR: Test if update method calls the handlers in order.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/tests/test_version_registry.py", line 111, in test_update
>     state = state_pickler.get_state(c)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 996, in get_state
>     s = dumps(obj)
>         ^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 968, in dumps
>     return StatePickler().dumps(value)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 308, in dumps
>     return pickle.dumps(self._do(value))
>                         ^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 358, in _do
>     return self._do_instance(obj)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_apptools/build/apptools/persistence/state_pickler.py", line 403, in _do_instance
>     state.pop("__traits_version__", None)
>     ^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'pop'
> 
> ----------------------------------------------------------------------
> Ran 355 tests in 1.754s
> 
> FAILED (errors=2)
```

Please note that every pyckable object has  \__getstate__  method in Python 3.11
[https://docs.python.org/3/library/pickle.html#object.\_\_getstate\_\_](https://docs.python.org/3/library/pickle.html#object.__getstate__)
As a consequence,  "else" statement is never hitted in this cycle:
https://github.com/enthought/apptools/blob/127fe9fe293c49c8a6626101bc3cf0684e163bf8/apptools/persistence/state_pickler.py#L395-L401

Kind Regards

**Comment by emollier** [comment]
Hi, I added the following [~fix~ workaround for python3.11 on Debian salsa](https://salsa.debian.org/python-team/packages/python-apptools/-/blob/debian/5.1.0-2/debian/patches/python3.11.patch); also uploaded.

Hope this helps,
Étienne.

**Comment by mdickinson** [comment]
Thanks for the report. We're planning some maintenance on apptools in the near-ish future, and that will include getting things back to working on Python 3.11.

**Comment by mdickinson** [comment]
For reference, the relevant change in CPython was this one: https://github.com/python/cpython/pull/2821
